### ISSUE TITLE
Update Docker-hub image

### ISSUE THREAD

**Issue by arnoid** [bitrise-docker/android-ndk#83]
Hey, guys.

The latest android-ndk build was 2 years ago.

Could you please update it to the latest release?

**Comment by viktorbenei** [comment]
We no longer use Docker hub auto build, we do custom builds and pushes, because this image is too large for Docker hub auto build. The last push was 4 days ago (we do weekly builds on the non alpha images): https://hub.docker.com/r/bitriseio/android-ndk/tags/

If you have any questions just let us know!

**Comment by viktorbenei** [comment]
P.S.: auto build is still presented on docker hub because as far as we know there's no option to turn an auto build repo/image into a non auto build one, so the UI still presents it as an auto build one, but we turned off auto builds and instead doing the builds on https://www.bitrise.io
